name: "Android x64 Build"
on:
  workflow_dispatch:
  push:
    branches:
      - AE
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  ORT_NIGHTLY_REST_API: "https://feeds.dev.azure.com/aiinfra/PublicPackages/_apis/packaging/Feeds/ORT-Nightly/packages?packageNameQuery=Microsoft.ML.OnnxRuntime&api-version=6.0-preview.1"
  ORT_PACKAGE_NAME: "Microsoft.ML.OnnxRuntime"
  ORT_NIGHTLY_SOURCE: "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/nuget/v3/index.json"
  ANDROID_ABI: "x86_64"

jobs:
  android_x64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout OnnxRuntime GenAI repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.6'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Install Android SDK command line tools
      - name: Install Android SDK command line tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip

          # Download and extract SDK tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip -d $HOME/android-sdk

          # Ensure correct path to cmdline-tools
          mv $HOME/android-sdk/cmdline-tools $HOME/android-sdk/cmdline-tools-latest

          # Export necessary environment variables
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$PATH:\$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

      # Ensure Android SDK tools are installed
      - name: Install Android SDK components
        run: |
          sdkmanager --update
          sdkmanager "platform-tools" "emulator" "system-images;android-27;default;x86_64" "platforms;android-27"

      # Create Android build
      - name: Create Android build
        run: |
          set -e -x
          rm -rf build
          ./build.sh --android --android_api=27 --android_ndk_path=${ANDROID_NDK_LATEST_HOME} --config=RelWithDebInfo --android_abi=${{ env.ANDROID_ABI }} --parallel --build_java --update

      # Run Android build
      - name: Run Android build
        run: |
          set -e -x
          ./build.sh --android --android_api=27 --android_ndk_path=${ANDROID_NDK_LATEST_HOME} --config=RelWithDebInfo --android_abi=${{ env.ANDROID_ABI }} --parallel --build_java --build

      # Enable KVM group perms so Android emulator can run
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Run the Android Emulator
      - name: Run Android Emulator
        run: |
          set -e -x
          $ANDROID_HOME/emulator/emulator -avd test_avd -no-window -no-audio -gpu off &
          adb wait-for-device

